In [1]:
import pandas as pd
from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_excel('./ev_market_2026_with_null.xlsx', engine='openpyxl')

In [3]:
df.head()

,brand,model,year,variant,price_usd,battery_capacity_kwh,range_miles,charging_speed_kw,acceleration_0_60_mph,top_speed_mph,...,body_type,cargo_volume_cubic_ft,weight_kg,safety_rating,autopilot_level,country_of_origin,market_segment,annual_sales_units,customer_rating,warranty_years
0,Volkswagen,ID. Buzz,2023,Performance,104880.80,118.7,400,234.5,3.04,195,...,Truck,54.2,2015,4,2,Germany,Luxury,202182.0,NaN,4.0
1,Toyota,bZ Compact SUV,2022,Premium,48217.41,58.8,219,148.1,5.77,159,...,SUV,69.0,1709,4,0,Japan,Mid-range,7146.0,3.56,3.0
2,GM/Chevrolet,Bolt EV,2024,Premium,49651.12,58.2,225,104.9,6.84,148,...,NaN,77.0,1533,4,1,US,Mid-range,16590.0,3.70,NaN
3,Kia,Sportage EV,2024,Long Range,38131.56,102.5,349,66.5,4.66,176,...,SUV,65.8,1935,4,2,South Korea,Mid-range,127201.0,3.81,3.0
4,Tesla,Model 3,2022,Long Range,144079.87,93.9,314,298.5,5.64,165,...,SUV,38.3,2229,4,2,US,Luxury,196401.0,3.83,4.0

In [4]:
df.shape

(2000, 24)

In [5]:
df.isnull().sum()

brand                    100
model                      0
year                       0
variant                    0
price_usd                  0
battery_capacity_kwh       0
range_miles                0
charging_speed_kw          0
acceleration_0_60_mph      0
top_speed_mph              0
horsepower                 0
torque_nm                  0
drive_type                 0
seating_capacity           0
body_type                100
cargo_volume_cubic_ft      0
weight_kg                  0
safety_rating              0
autopilot_level            0
country_of_origin          0
market_segment             0
annual_sales_units       100
customer_rating          100
warranty_years           100
dtype: int64

**TRATAR VALORES NULOS DA COLUNA: brand**

In [6]:
df[pd.isnull(df['brand'])]

,brand,model,year,variant,price_usd,battery_capacity_kwh,range_miles,charging_speed_kw,acceleration_0_60_mph,top_speed_mph,...,body_type,cargo_volume_cubic_ft,weight_kg,safety_rating,autopilot_level,country_of_origin,market_segment,annual_sales_units,customer_rating,warranty_years
10,NaN,Model S,2026,Long Range,134165.81,103.2,347,324.4,4.56,187,...,Sedan,26.7,1720,4,2,US,Luxury,NaN,3.78,4.0
15,NaN,Model S,2024,Premium,134964.13,67.4,250,343.3,7.46,135,...,Van,76.0,1500,5,2,US,Luxury,235048.0,3.81,NaN
18,NaN,ID.4,2024,Long Range,77030.00,88.0,332,118.8,4.75,183,...,Sedan,38.7,1634,4,0,Germany,Premium,238587.0,3.37,4.0
46,NaN,Atto 3,2025,Base,26682.38,53.9,199,117.3,7.39,137,...,Truck,68.8,2367,4,0,China,Budget,158602.0,3.26,3.0
59,NaN,Leaf 50X,2025,Base,59005.52,58.4,200,121.5,7.64,137,...,Van,76.9,1500,5,0,China,Mid-range,127516.0,3.31,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1918,NaN,ID.4,2022,Performance,97372.99,74.1,240,226.0,2.50,200,...,Sedan,26.0,1616,4,0,Germany,Premium,246097.0,NaN,4.0
1928,NaN,i3,2024,Performance,123235.74,117.3,428,187.9,3.59,186,...,Truck,54.0,2571,5,1,Germany,Luxury,49531.0,3.97,6.0
1933,NaN,Sportage EV,2025,Premium,89200.56,62.2,211,64.2,6.77,149,...,SUV,37.1,2168,4,1,South Korea,Premium,55676.0,3.00,5.0
1955,NaN,R2,2025,Long Range,102186.85,81.0,292,92.6,4.50,180,...,Hatchback,30.2,1603,5,0,US,Luxury,NaN,3.37,4.0
1983,NaN,Ioniq,2026,Standard,37257.29,52.5,164,104.7,5.96,160,...,SUV,43.0,2264,3,1,South Korea,Mid-range,64933.0,NaN,5.0

In [7]:
df_grouped_brand_model = df.groupby(['brand', 'model']).agg({'price_usd':'mean'}).reset_index()

In [8]:
df_grouped_brand_model

         brand          model      price_usd
0         Audi      Q4 e-tron  100528.756111
1         Audi      Q6 e-tron   92604.855556
2         Audi         e-tron   92489.162105
3         Audi      e-tron GT   89522.063684
4          BMW             i3  101895.503889
..         ...            ...            ...
71  Volkswagen           ID.5   64827.305769
72       Volvo   C40 Recharge   61998.472500
73       Volvo  XC40 Recharge   95499.130000
74       Volvo  XC90 Recharge   83247.901667
75      Xiaomi            SU7   82234.972857

[76 rows x 3 columns]

In [9]:
brand_model_dict = {}
for index, row in df_grouped_brand_model.iterrows():
  brand_model_dict[row['model']] = row['brand']

In [10]:
brand_model_dict['Model S']

'Tesla'

In [11]:
brand_model_dict['Leaf 50X']

'BYD'

In [12]:
brand_model_dict['Atto 3']

'BYD'

In [13]:
brand_model_dict['ID.4']

'Volkswagen'

In [14]:
def fill_brand(brand, model, brand_model_dict):
  if pd.isnull(brand):
    return brand_model_dict[model]
  else:
    return brand

In [15]:
df[['brand', 'model']].apply(lambda x : fill_brand(x['brand'], x['model'], brand_model_dict), axis=1).iloc[[10, 15, 18, 46, 59]]

10         Tesla
15         Tesla
18    Volkswagen
46           BYD
59           BYD
dtype: object

In [16]:
df['brand'] = df[['brand', 'model']].apply(lambda x : fill_brand(x['brand'], x['model'], brand_model_dict), axis=1)

In [17]:
df[pd.isnull(df['brand'])]

Empty DataFrame
Columns: [brand, model, year, variant, price_usd, battery_capacity_kwh, range_miles, charging_speed_kw, acceleration_0_60_mph, top_speed_mph, horsepower, torque_nm, drive_type, seating_capacity, body_type, cargo_volume_cubic_ft, weight_kg, safety_rating, autopilot_level, country_of_origin, market_segment, annual_sales_units, customer_rating, warranty_years]
Index: []

[0 rows x 24 columns]

In [18]:
df.isnull().sum()

brand                      0
model                      0
year                       0
variant                    0
price_usd                  0
battery_capacity_kwh       0
range_miles                0
charging_speed_kw          0
acceleration_0_60_mph      0
top_speed_mph              0
horsepower                 0
torque_nm                  0
drive_type                 0
seating_capacity           0
body_type                100
cargo_volume_cubic_ft      0
weight_kg                  0
safety_rating              0
autopilot_level            0
country_of_origin          0
market_segment             0
annual_sales_units       100
customer_rating          100
warranty_years           100
dtype: int64

In [19]:
df

,brand,model,year,variant,price_usd,battery_capacity_kwh,range_miles,charging_speed_kw,acceleration_0_60_mph,top_speed_mph,...,body_type,cargo_volume_cubic_ft,weight_kg,safety_rating,autopilot_level,country_of_origin,market_segment,annual_sales_units,customer_rating,warranty_years
0,Volkswagen,ID. Buzz,2023,Performance,104880.80,118.7,400,234.5,3.04,195,...,Truck,54.2,2015,4,2,Germany,Luxury,202182.0,NaN,4.0
1,Toyota,bZ Compact SUV,2022,Premium,48217.41,58.8,219,148.1,5.77,159,...,SUV,69.0,1709,4,0,Japan,Mid-range,7146.0,3.56,3.0
2,GM/Chevrolet,Bolt EV,2024,Premium,49651.12,58.2,225,104.9,6.84,148,...,NaN,77.0,1533,4,1,US,Mid-range,16590.0,3.70,NaN
3,Kia,Sportage EV,2024,Long Range,38131.56,102.5,349,66.5,4.66,176,...,SUV,65.8,1935,4,2,South Korea,Mid-range,127201.0,3.81,3.0
4,Tesla,Model 3,2022,Long Range,144079.87,93.9,314,298.5,5.64,165,...,SUV,38.3,2229,4,2,US,Luxury,196401.0,3.83,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,BMW,i3,2023,Long Range,122665.71,102.1,360,92.0,4.21,190,...,Hatchback,38.3,1500,5,2,Germany,Luxury,66187.0,3.78,7.0
1996,Toyota,bZ4X,2024,Performance,66816.55,110.6,367,236.3,4.25,181,...,Hatchback,23.1,1863,4,0,Japan,Premium,11062.0,3.79,4.0
1997,Tesla,Model 3,2025,Long Range,49281.26,90.6,325,325.6,5.55,167,...,Truck,74.6,2920,3,3,US,Mid-range,224804.0,4.10,NaN
1998,Tesla,Model X,2026,Premium,139665.73,70.7,248,330.7,5.07,175,...,Coupe,34.8,1500,3,2,US,Luxury,165373.0,3.66,4.0
1999,BYD,Qin,2025,Premium,47547.88,67.4,246,67.2,6.76,156,...,Coupe,28.5,1512,4,0,China,Mid-range,214113.0,3.41,4.0

In [20]:
df[pd.isnull(df['body_type'])]

,brand,model,year,variant,price_usd,battery_capacity_kwh,range_miles,charging_speed_kw,acceleration_0_60_mph,top_speed_mph,...,body_type,cargo_volume_cubic_ft,weight_kg,safety_rating,autopilot_level,country_of_origin,market_segment,annual_sales_units,customer_rating,warranty_years
2,GM/Chevrolet,Bolt EV,2024,Premium,49651.12,58.2,225,104.9,6.84,148,...,NaN,77.0,1533,4,1,US,Mid-range,16590.0,3.70,NaN
31,Tesla,Model X,2025,Base,110771.86,52.9,177,216.7,6.55,151,...,NaN,35.7,1959,4,2,US,Luxury,179640.0,3.42,5.0
63,Volkswagen,ID.4,2023,Long Range,94330.19,105.4,383,105.8,5.17,177,...,NaN,21.8,1500,5,1,Germany,Premium,NaN,3.95,3.0
146,Kia,Sportage EV,2025,Performance,99993.15,93.7,336,154.0,3.15,196,...,NaN,39.6,2114,4,1,South Korea,Premium,NaN,3.59,3.0
187,Kia,EV9,2024,Premium,65472.17,78.2,224,99.0,7.54,133,...,NaN,55.0,2132,4,0,South Korea,Premium,60682.0,3.30,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909,Tesla,Model S,2025,Performance,169177.37,89.9,303,309.6,3.53,200,...,NaN,66.8,2131,4,3,US,Luxury,130032.0,3.68,NaN
1961,Volkswagen,ID.4,2023,Long Range,78653.83,94.4,350,75.5,4.49,189,...,NaN,25.0,1665,5,0,Germany,Premium,NaN,3.97,4.0
1965,Kia,Picanto EV,2022,Long Range,73622.08,94.4,291,141.7,4.02,187,...,NaN,41.4,1901,5,2,South Korea,Premium,128389.0,3.38,4.0
1966,Tesla,Cybertruck,2026,Performance,70200.56,85.0,286,209.3,3.65,189,...,NaN,73.4,2486,5,2,US,Premium,166507.0,NaN,4.0
1987,Hyundai,Ioniq 5,2023,Long Range,41738.10,88.1,330,140.9,5.47,167,...,NaN,36.5,1697,5,0,South Korea,Mid-range,92151.0,3.69,4.0


**TRATAR VALORES NULOS DA COLUNA: body_type**

In [28]:
df[pd.isnull(df['body_type'])]

,brand,model,year,variant,price_usd,battery_capacity_kwh,range_miles,charging_speed_kw,acceleration_0_60_mph,top_speed_mph,...,body_type,cargo_volume_cubic_ft,weight_kg,safety_rating,autopilot_level,country_of_origin,market_segment,annual_sales_units,customer_rating,warranty_years
2,GM/Chevrolet,Bolt EV,2024,Premium,49651.12,58.2,225,104.9,6.84,148,...,NaN,77.0,1533,4,1,US,Mid-range,16590.0,3.70,NaN
31,Tesla,Model X,2025,Base,110771.86,52.9,177,216.7,6.55,151,...,NaN,35.7,1959,4,2,US,Luxury,179640.0,3.42,5.0
63,Volkswagen,ID.4,2023,Long Range,94330.19,105.4,383,105.8,5.17,177,...,NaN,21.8,1500,5,1,Germany,Premium,NaN,3.95,3.0
146,Kia,Sportage EV,2025,Performance,99993.15,93.7,336,154.0,3.15,196,...,NaN,39.6,2114,4,1,South Korea,Premium,NaN,3.59,3.0
187,Kia,EV9,2024,Premium,65472.17,78.2,224,99.0,7.54,133,...,NaN,55.0,2132,4,0,South Korea,Premium,60682.0,3.30,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909,Tesla,Model S,2025,Performance,169177.37,89.9,303,309.6,3.53,200,...,NaN,66.8,2131,4,3,US,Luxury,130032.0,3.68,NaN
1961,Volkswagen,ID.4,2023,Long Range,78653.83,94.4,350,75.5,4.49,189,...,NaN,25.0,1665,5,0,Germany,Premium,NaN,3.97,4.0
1965,Kia,Picanto EV,2022,Long Range,73622.08,94.4,291,141.7,4.02,187,...,NaN,41.4,1901,5,2,South Korea,Premium,128389.0,3.38,4.0
1966,Tesla,Cybertruck,2026,Performance,70200.56,85.0,286,209.3,3.65,189,...,NaN,73.4,2486,5,2,US,Premium,166507.0,NaN,4.0
1987,Hyundai,Ioniq 5,2023,Long Range,41738.10,88.1,330,140.9,5.47,167,...,NaN,36.5,1697,5,0,South Korea,Mid-range,92151.0,3.69,4.0

In [ ]:
# Filtra os dados removendo os nulos apenas para construir o dicionário confiável

In [29]:
df_valid_body = df.dropna(subset=['body_type'])

In [ ]:
# Agrupa por modelo e body_type

In [30]:
df_grouped_model_body = df_valid_body.groupby(['model', 'body_type']).size().reset_index()

In [31]:
df_grouped_model_body

    model  body_type  0
0       2      Coupe  1
1       2  Hatchback  1
2       2        Van  1
3       3      Coupe  1
4       3  Hatchback  1
..    ...        ... ..
353    iX  Hatchback  6
354    iX        SUV  5
355    iX      Sedan  4
356    iX      Truck  2
357    iX        Van  6

[358 rows x 3 columns]

In [ ]:
# Cria o dicionário iterando sobre o agrupamento

In [32]:
model_body_dict = {}
for index, row in df_grouped_model_body.iterrows():
  model_body_dict[row['model']] = row['body_type']

In [33]:
def fill_body_type(body_type, model, model_body_dict):
  if pd.isnull(body_type):
    return model_body_dict.get(model, body_type)
  else:
    return body_type

In [34]:
df[['body_type', 'model']].apply(lambda x: fill_body_type(x['body_type'], x['model'], model_body_dict), axis=1).iloc[[2, 31, 63, 146, 187]]

2      Van
31     Van
63     Van
146    SUV
187    SUV
dtype: object

In [35]:
df['body_type'] = df.apply(lambda x : fill_body_type(x['body_type'], x['model'], model_body_dict), axis=1)

In [36]:
df[pd.isnull(df['body_type'])]

Empty DataFrame
Columns: [brand, model, year, variant, price_usd, battery_capacity_kwh, range_miles, charging_speed_kw, acceleration_0_60_mph, top_speed_mph, horsepower, torque_nm, drive_type, seating_capacity, body_type, cargo_volume_cubic_ft, weight_kg, safety_rating, autopilot_level, country_of_origin, market_segment, annual_sales_units, customer_rating, warranty_years]
Index: []

[0 rows x 24 columns]

In [37]:
df.isnull().sum()

brand                      0
model                      0
year                       0
variant                    0
price_usd                  0
battery_capacity_kwh       0
range_miles                0
charging_speed_kw          0
acceleration_0_60_mph      0
top_speed_mph              0
horsepower                 0
torque_nm                  0
drive_type                 0
seating_capacity           0
body_type                  0
cargo_volume_cubic_ft      0
weight_kg                  0
safety_rating              0
autopilot_level            0
country_of_origin          0
market_segment             0
annual_sales_units       100
customer_rating          100
warranty_years           100
dtype: int64

**TRATAR VALOR NULOS DA COLUNA: annual_sales_units**

In [39]:
df[pd.isnull(df['annual_sales_units'])]

,brand,model,year,variant,price_usd,battery_capacity_kwh,range_miles,charging_speed_kw,acceleration_0_60_mph,top_speed_mph,...,body_type,cargo_volume_cubic_ft,weight_kg,safety_rating,autopilot_level,country_of_origin,market_segment,annual_sales_units,customer_rating,warranty_years
10,Tesla,Model S,2026,Long Range,134165.81,103.2,347,324.4,4.56,187,...,Sedan,26.7,1720,4,2,US,Luxury,NaN,3.78,4.0
11,Fisker,Ronin,2025,Standard,88914.19,66.7,232,129.5,5.10,173,...,Truck,64.7,2536,3,2,US,Premium,NaN,3.67,5.0
26,Tesla,Model X,2023,Standard,67772.81,53.3,175,320.5,7.79,128,...,Sedan,28.7,1539,5,2,US,Premium,NaN,3.36,6.0
51,Ford,F-150 Lightning,2026,Base,52266.72,73.4,268,58.4,7.42,137,...,Truck,50.3,2850,5,0,US,Mid-range,NaN,3.72,3.0
63,Volkswagen,ID.4,2023,Long Range,94330.19,105.4,383,105.8,5.17,177,...,Van,21.8,1500,5,1,Germany,Premium,NaN,3.95,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1955,Rivian,R2,2025,Long Range,102186.85,81.0,292,92.6,4.50,180,...,Hatchback,30.2,1603,5,0,US,Luxury,NaN,3.37,4.0
1961,Volkswagen,ID.4,2023,Long Range,78653.83,94.4,350,75.5,4.49,189,...,Van,25.0,1665,5,0,Germany,Premium,NaN,3.97,4.0
1967,Volkswagen,ID. Aero,2025,Performance,86735.20,77.5,296,203.5,4.31,188,...,Van,72.5,1665,5,0,Germany,Premium,NaN,3.15,3.0
1973,Hyundai,Kona Electric,2025,Long Range,92989.48,91.0,315,115.3,5.49,166,...,SUV,50.4,1766,5,2,South Korea,Premium,NaN,3.62,4.0
1979,Mercedes,EQE,2026,Premium,93286.78,82.1,282,142.9,7.41,136,...,Hatchback,37.5,1500,3,1,Germany,Premium,NaN,3.74,8.0

**Preencher com valor fixo**

In [ ]:
#df.fillna({'annual_sales_units':1}, inplace=True)

**Preencher com a média, mediana, moda**

In [ ]:
#Possibilidades: mean, median, most_frequent, constant
#imputer = SimpleImputer(strategy='mean')

In [ ]:
#df['annual_sales_units'] = imputer.fit_transform(df[['annual_sales_units']])

In [ ]:
#df.isnull().sum()

In [40]:
df.iloc[[10, 11, 26, 51, 63]]

,brand,model,year,variant,price_usd,battery_capacity_kwh,range_miles,charging_speed_kw,acceleration_0_60_mph,top_speed_mph,...,body_type,cargo_volume_cubic_ft,weight_kg,safety_rating,autopilot_level,country_of_origin,market_segment,annual_sales_units,customer_rating,warranty_years
10,Tesla,Model S,2026,Long Range,134165.81,103.2,347,324.4,4.56,187,...,Sedan,26.7,1720,4,2,US,Luxury,NaN,3.78,4.0
11,Fisker,Ronin,2025,Standard,88914.19,66.7,232,129.5,5.10,173,...,Truck,64.7,2536,3,2,US,Premium,NaN,3.67,5.0
26,Tesla,Model X,2023,Standard,67772.81,53.3,175,320.5,7.79,128,...,Sedan,28.7,1539,5,2,US,Premium,NaN,3.36,6.0
51,Ford,F-150 Lightning,2026,Base,52266.72,73.4,268,58.4,7.42,137,...,Truck,50.3,2850,5,0,US,Mid-range,NaN,3.72,3.0
63,Volkswagen,ID.4,2023,Long Range,94330.19,105.4,383,105.8,5.17,177,...,Van,21.8,1500,5,1,Germany,Premium,NaN,3.95,3.0

In [41]:
df.groupby(['brand', 'model', 'body_type', 'market_segment']).agg({'annual_sales_units':'mean'}).reset_index()

      brand      model  body_type market_segment  annual_sales_units
0      Audi  Q4 e-tron      Coupe         Luxury             21092.0
1      Audi  Q4 e-tron  Hatchback      Mid-range             48087.0
2      Audi  Q4 e-tron  Hatchback        Premium             52901.0
3      Audi  Q4 e-tron        SUV         Luxury             57074.0
4      Audi  Q4 e-tron        SUV      Mid-range             57366.0
..      ...        ...        ...            ...                 ...
787  Xiaomi        SU7        SUV         Luxury              8357.0
788  Xiaomi        SU7        SUV      Mid-range             22178.0
789  Xiaomi        SU7        SUV        Premium             18923.5
790  Xiaomi        SU7      Sedan      Mid-range             22327.0
791  Xiaomi        SU7      Truck        Premium             26829.0

[792 rows x 5 columns]

In [ ]:
# O transform calcula as médias baseado no grupo, mas mantém o tamanho exato da tabela original

In [42]:
medias_calculadas = df.groupby(['brand', 'model', 'body_type', 'market_segment'])['annual_sales_units'].transform('mean')

In [ ]:
# Agora pedimos para o Pandas preencher os nulos da coluna original usando essas médias

In [43]:
df['annual_sales_units'] = df['annual_sales_units'].fillna(medias_calculadas)

In [44]:
df.isnull().sum()

brand                      0
model                      0
year                       0
variant                    0
price_usd                  0
battery_capacity_kwh       0
range_miles                0
charging_speed_kw          0
acceleration_0_60_mph      0
top_speed_mph              0
horsepower                 0
torque_nm                  0
drive_type                 0
seating_capacity           0
body_type                  0
cargo_volume_cubic_ft      0
weight_kg                  0
safety_rating              0
autopilot_level            0
country_of_origin          0
market_segment             0
annual_sales_units        21
customer_rating          100
warranty_years           100
dtype: int64

In [ ]:
# PLANO B: Afunilando o agrupamento de dados. Vamos calcular a média apenas por Marca e Segmento

In [49]:
medias_marca_segmento = df.groupby(['brand', 'market_segment'])['annual_sales_units'].transform('mean')
df['annual_sales_units'] = df['annual_sales_units'].fillna(medias_marca_segmento)

In [50]:
df.isnull().sum()

brand                      0
model                      0
year                       0
variant                    0
price_usd                  0
battery_capacity_kwh       0
range_miles                0
charging_speed_kw          0
acceleration_0_60_mph      0
top_speed_mph              0
horsepower                 0
torque_nm                  0
drive_type                 0
seating_capacity           0
body_type                  0
cargo_volume_cubic_ft      0
weight_kg                  0
safety_rating              0
autopilot_level            0
country_of_origin          0
market_segment             0
annual_sales_units         0
customer_rating          100
warranty_years           100
dtype: int64

**TRATAR VALORES NULOS DA COLUNA: customer_rating**

In [51]:
df[pd.isnull(df['customer_rating'])]

,brand,model,year,variant,price_usd,battery_capacity_kwh,range_miles,charging_speed_kw,acceleration_0_60_mph,top_speed_mph,...,body_type,cargo_volume_cubic_ft,weight_kg,safety_rating,autopilot_level,country_of_origin,market_segment,annual_sales_units,customer_rating,warranty_years
0,Volkswagen,ID. Buzz,2023,Performance,104880.80,118.7,400,234.5,3.04,195,...,Truck,54.2,2015,4,2,Germany,Luxury,202182.0,NaN,4.0
40,Tesla,Cybertruck,2024,Standard,121805.30,58.9,204,274.6,5.61,173,...,Truck,56.2,2502,4,3,US,Luxury,225373.0,NaN,5.0
76,Ford,Mustang Mach-E,2024,Standard,79438.20,82.5,299,128.6,6.77,149,...,Van,80.0,1521,5,0,US,Premium,21827.0,NaN,3.0
80,Mercedes,GLE EV,2023,Standard,144581.79,42.8,150,146.8,6.34,156,...,SUV,57.7,1857,4,1,Germany,Luxury,76491.0,NaN,NaN
107,GM/Chevrolet,Bolt EUV,2024,Premium,43668.28,79.4,284,108.1,7.81,120,...,Truck,60.3,2572,4,1,US,Mid-range,1211.0,NaN,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1966,Tesla,Cybertruck,2026,Performance,70200.56,85.0,286,209.3,3.65,189,...,Truck,73.4,2486,5,2,US,Premium,166507.0,NaN,4.0
1970,Tesla,Model 3,2024,Premium,128470.34,75.7,268,263.7,7.17,140,...,Truck,77.7,2712,3,2,US,Luxury,244654.0,NaN,6.0
1980,Tesla,Model X,2023,Performance,164467.67,113.9,371,279.4,3.22,200,...,Van,66.0,1822,5,2,US,Luxury,146842.0,NaN,4.0
1983,Hyundai,Ioniq,2026,Standard,37257.29,52.5,164,104.7,5.96,160,...,SUV,43.0,2264,3,1,South Korea,Mid-range,64933.0,NaN,5.0
1990,Ford,E-Transit,2025,Base,61660.35,67.9,221,89.6,5.21,167,...,Coupe,27.1,1660,4,2,US,Mid-range,27087.0,NaN,5.0

In [ ]:
# Calcula a média de 'customer_rating' agrupando por 'brand' , 'model'

In [52]:
medias_rating = df.groupby(['brand', 'model'])['customer_rating'].transform('mean')

In [ ]:
# Preenchendo os valores nulos com as médias calculadas

In [53]:
df['customer_rating'] = df['customer_rating'].fillna(medias_rating)

In [54]:
df.isnull().sum()

brand                      0
model                      0
year                       0
variant                    0
price_usd                  0
battery_capacity_kwh       0
range_miles                0
charging_speed_kw          0
acceleration_0_60_mph      0
top_speed_mph              0
horsepower                 0
torque_nm                  0
drive_type                 0
seating_capacity           0
body_type                  0
cargo_volume_cubic_ft      0
weight_kg                  0
safety_rating              0
autopilot_level            0
country_of_origin          0
market_segment             0
annual_sales_units         0
customer_rating            0
warranty_years           100
dtype: int64

**TRATAR VALORES NULOS DA COLUNA: warranty_years**

In [55]:
df[pd.isnull(df['warranty_years'])]

,brand,model,year,variant,price_usd,battery_capacity_kwh,range_miles,charging_speed_kw,acceleration_0_60_mph,top_speed_mph,...,body_type,cargo_volume_cubic_ft,weight_kg,safety_rating,autopilot_level,country_of_origin,market_segment,annual_sales_units,customer_rating,warranty_years
2,GM/Chevrolet,Bolt EV,2024,Premium,49651.12,58.2,225,104.9,6.84,148,...,Van,77.0,1533,4,1,US,Mid-range,16590.0,3.70,NaN
15,Tesla,Model S,2024,Premium,134964.13,67.4,250,343.3,7.46,135,...,Van,76.0,1500,5,2,US,Luxury,235048.0,3.81,NaN
32,Tesla,Cybertruck,2024,Performance,42827.24,89.9,311,240.1,2.94,200,...,Truck,55.5,2122,4,3,US,Mid-range,133489.0,3.82,NaN
65,Kia,Niro EV,2024,Premium,68436.66,70.0,249,131.3,7.12,141,...,Coupe,23.0,1556,3,0,South Korea,Premium,81219.0,3.63,NaN
72,Tesla,Model S,2020,Performance,102900.51,74.1,231,323.4,2.61,200,...,Truck,79.8,2284,3,2,US,Luxury,184383.0,3.80,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1887,BYD,Dolphin,2025,Base,64952.61,79.2,299,135.5,7.42,144,...,Coupe,35.0,1563,5,2,China,Mid-range,246706.0,3.79,NaN
1909,Tesla,Model S,2025,Performance,169177.37,89.9,303,309.6,3.53,200,...,Van,66.8,2131,4,3,US,Luxury,130032.0,3.68,NaN
1911,Audi,Q4 e-tron,2023,Base,48523.32,82.6,283,91.7,7.19,137,...,SUV,55.9,2208,5,2,Germany,Mid-range,57366.0,3.57,NaN
1935,Ford,Explorer EV,2025,Performance,63490.76,108.0,370,240.1,3.78,196,...,Sedan,32.3,1500,4,0,US,Mid-range,37708.0,3.81,NaN
1997,Tesla,Model 3,2025,Long Range,49281.26,90.6,325,325.6,5.55,167,...,Truck,74.6,2920,3,3,US,Mid-range,224804.0,4.10,NaN

In [ ]:
# Calculando a média de 'warranty_years' agrupando por 'brand' e 'model'

In [56]:
medias_warranty = df.groupby(['brand', 'model'])['warranty_years'].transform('mean')

In [ ]:
# Preenchendo os valores nulos com as médias calculadas

In [57]:
df['warranty_years'] = df['warranty_years'].fillna(medias_warranty)

In [58]:
df.isnull().sum()

brand                    0
model                    0
year                     0
variant                  0
price_usd                0
battery_capacity_kwh     0
range_miles              0
charging_speed_kw        0
acceleration_0_60_mph    0
top_speed_mph            0
horsepower               0
torque_nm                0
drive_type               0
seating_capacity         0
body_type                0
cargo_volume_cubic_ft    0
weight_kg                0
safety_rating            0
autopilot_level          0
country_of_origin        0
market_segment           0
annual_sales_units       0
customer_rating          0
warranty_years           1
dtype: int64

In [ ]:
# PLANO B: Afunilando o agrupamento dos dados. Vamos calcular a média apenas por Marca e Segmento

In [59]:
medias_warranty_marca_segmento = df.groupby(['brand', 'market_segment'])['warranty_years'].transform('mean')

In [ ]:
# Preenchendo os nulos restantes

In [60]:
df['warranty_years'] = df['warranty_years'].fillna(medias_warranty_marca_segmento)

In [61]:
df.isnull().sum()

brand                    0
model                    0
year                     0
variant                  0
price_usd                0
battery_capacity_kwh     0
range_miles              0
charging_speed_kw        0
acceleration_0_60_mph    0
top_speed_mph            0
horsepower               0
torque_nm                0
drive_type               0
seating_capacity         0
body_type                0
cargo_volume_cubic_ft    0
weight_kg                0
safety_rating            0
autopilot_level          0
country_of_origin        0
market_segment           0
annual_sales_units       0
customer_rating          0
warranty_years           0
dtype: int64